### ISSUE TITLE
Fail on error mode

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/action#2]
**Is your feature request related to a problem? Please describe.**
At the moment, the action ignores the errors returned by the engine runners. 

**Describe the solution you'd like**
In connection to https://github.com/reviewpad/reviewpad/issues/28, the action should fail or not depending on the value of the `fail-on-error` property and if the engine runner returned an error.

**Describe alternatives you've considered**
None. 

**Additional context**
None.

**Comment by shay2025** [comment]
The property `fail-on-error` will be named `ignore-errors`.
