### ISSUE TITLE
Reviewpad action output with "missing variable INPUT_TOKEN"

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/action#25]
**Describe the bug**
It can happen that when running reviewpad action the action fails with the message `missing variable INPUT_TOKEN`. Here's an example - https://github.com/reviewpad/reviewpad/runs/7852917856?check_suite_focus=true

We need to understand **why** this is happening and how to **solve** it.

`INPUT_TOKEN` is the toke provided by github when running the reviewpad action - https://github.com/reviewpad/action/blob/main/action.yml#L19

**To Reproduce**
This behavior is not predictable but we can find it in some places. Heres's [one](https://github.com/reviewpad/reviewpad/runs/7852917856?check_suite_focus=true).

Please not that this happened for an event from `Reviewpad / reviewpad (pull_request_review)`.

**Expected behavior**
The action shouldn't fail.

**Screenshots**
<img width="2021" alt="image" src="https://user-images.githubusercontent.com/3806676/184824309-24f7f0ac-77f9-40f0-9acd-a3049b6f6d73.png">

**Comment by marcelosousa** [comment]
It seems that it only happens on pull requests from forks.

**Comment by marcelosousa** [comment]
Known limitation of using `pull_request_review` with forks: https://github.com/orgs/community/discussions/26651

**Comment by marcelosousa** [comment]
At this stage, there is not much we can do with the GitHub Action because this is a known limitation from GitHub. For this reason, closing this issue for now.
